micronaut:
  application:
    name: api
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  http:
    client:
      exception-on-error-status: false
datasources:
  hikari:
    url: 'jdbc:mysql://localhost:3306'
    username: 'user'
    password: 'password'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    connection-timeout: 2000
    initialization-fail-timeout: -1

jpa:
  hikari:
    properties:
      hibernate:
        ddl-auto: none
        hbm2ddl:
          auto: none
        show_sql: true

netty:
  default:
    allocator:
      max-order: 3
